# Generated by Django 2.1.15 on 2021-07-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, max_length=36, null=True)),
                ('sum', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'Vadym].[Orders',
            },
        ),
    ]
